## Objective:
###  Processing Data and Predicting Grades by training different machine learning model.

In [2]:
import pandas as pd
import numpy as np

In [14]:
df_mat = pd.read_csv('data/student-mat.csv')
df_por = pd.read_csv('data/student-por.csv')

## A. Lets look at the data

In [15]:
df_mat.head()

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other ...   
3     GP   F   15       U     GT3       T     4     2   health  services ...   
4     GP   F   16       U     GT3       T     3     3    other     other ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        6   5   6   6  
1      5        3      3     1     1      3        4   5   5   6  
2      4        3      2     2     3      3       10   7   8  10  
3      3        2      2     1     1      5        2  15  14  15  
4      4        3      2     1     2      5        4   6  10  10  

[5 rows x 33 columns]

In [16]:
df_mat.describe()

age        Medu        Fedu  traveltime   studytime    failures  \
count  395.000000  395.000000  395.000000  395.000000  395.000000  395.000000   
mean    16.696203    2.749367    2.521519    1.448101    2.035443    0.334177   
std      1.276043    1.094735    1.088201    0.697505    0.839240    0.743651   
min     15.000000    0.000000    0.000000    1.000000    1.000000    0.000000   
25%     16.000000    2.000000    2.000000    1.000000    1.000000    0.000000   
50%     17.000000    3.000000    2.000000    1.000000    2.000000    0.000000   
75%     18.000000    4.000000    3.000000    2.000000    2.000000    0.000000   
max     22.000000    4.000000    4.000000    4.000000    4.000000    3.000000   

           famrel    freetime       goout        Dalc        Walc      health  \
count  395.000000  395.000000  395.000000  395.000000  395.000000  395.000000   
mean     3.944304    3.235443    3.108861    1.481013    2.291139    3.554430   
std      0.896659    0.998862    1.113278    0.890741    1.287897    1.390303   
min      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   
25%      4.000000    3.000000    2.000000    1.000000    1.000000    3.000000   
50%      4.000000    3.000000    3.000000    1.000000    2.000000    4.000000   
75%      5.000000    4.000000    4.000000    2.000000    3.000000    5.000000   
max      5.000000    5.000000    5.000000    5.000000    5.000000    5.000000   

         absences          G1          G2          G3  
count  395.000000  395.000000  395.000000  395.000000  
mean     5.708861   10.908861   10.713924   10.415190  
std      8.003096    3.319195    3.761505    4.581443  
min      0.000000    3.000000    0.000000    0.000000  
25%      0.000000    8.000000    9.000000    8.000000  
50%      4.000000   11.000000   11.000000   11.000000  
75%      8.000000   13.000000   13.000000   14.000000  
max     75.000000   19.000000   19.000000   20.000000

In [17]:
# checking for null values
df_mat.isnull().sum()

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

In [18]:
# checking for null values
df_mat.isnull().sum()

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

## So, data is clean. There is no null value

## B. Data Preprocessing

In [19]:
# combining data
df = pd.merge(df_mat, df_por, how = 'outer')
df.describe()

age         Medu         Fedu   traveltime    studytime  \
count  1044.000000  1044.000000  1044.000000  1044.000000  1044.000000   
mean     16.726054     2.603448     2.387931     1.522989     1.970307   
std       1.239975     1.124907     1.099938     0.731727     0.834353   
min      15.000000     0.000000     0.000000     1.000000     1.000000   
25%      16.000000     2.000000     1.000000     1.000000     1.000000   
50%      17.000000     3.000000     2.000000     1.000000     2.000000   
75%      18.000000     4.000000     3.000000     2.000000     2.000000   
max      22.000000     4.000000     4.000000     4.000000     4.000000   

          failures       famrel     freetime        goout         Dalc  \
count  1044.000000  1044.000000  1044.000000  1044.000000  1044.000000   
mean      0.264368     3.935824     3.201149     3.156130     1.494253   
std       0.656142     0.933401     1.031507     1.152575     0.911714   
min       0.000000     1.000000     1.000000     1.000000     1.000000   
25%       0.000000     4.000000     3.000000     2.000000     1.000000   
50%       0.000000     4.000000     3.000000     3.000000     1.000000   
75%       0.000000     5.000000     4.000000     4.000000     2.000000   
max       3.000000     5.000000     5.000000     5.000000     5.000000   

              Walc       health     absences           G1           G2  \
count  1044.000000  1044.000000  1044.000000  1044.000000  1044.000000   
mean      2.284483     3.543103     4.434866    11.213602    11.246169   
std       1.285105     1.424703     6.210017     2.983394     3.285071   
min       1.000000     1.000000     0.000000     0.000000     0.000000   
25%       1.000000     3.000000     0.000000     9.000000     9.000000   
50%       2.000000     4.000000     2.000000    11.000000    11.000000   
75%       3.000000     5.000000     6.000000    13.000000    13.000000   
max       5.000000     5.000000    75.000000    19.000000    19.000000   

                G3  
count  1044.000000  
mean     11.341954  
std       3.864796  
min       0.000000  
25%      10.000000  
50%      11.000000  
75%      14.000000  
max      20.000000

In [20]:
# data which has only 2 possible values
df['rural'] = (df['address'] == 'R').astype(int)
df = df.drop(['address'], axis = 1)
df['P_apart'] = (df['Pstatus'] == 'A').astype(int)
df = df.drop(['Pstatus'], axis = 1)
df['school_GP'] = (df['school'] == 'GP').astype(int)
df = df.drop(['school'], axis = 1)
df['female'] = (df['sex'] == 'F').astype(int)
df = df.drop(['sex'], axis = 1)
df['famsize_bin'] = (df['famsize'] == 'LE3').astype(int)
df = df.drop(['famsize'], axis = 1)

In [21]:
# hot-encoding remaining data
df['guardian_mother'] = (df['guardian'] == 'mother').astype(int)
df['guardian_father'] = (df['guardian'] == 'father').astype(int)
df = df.drop(['guardian'], axis = 1)

df['Mjob_at_home'] = (df['Mjob'] == 'at_home').astype(int)
df['Mjob_health'] = (df['Mjob'] == 'health').astype(int)
df['Mjob_teacher'] = (df['Mjob'] == 'teacher').astype(int)
df['Mjob_services'] = (df['Mjob'] == 'services').astype(int)
df = df.drop(['Mjob'], axis = 1)

df['Fjob_at_home'] = (df['Fjob'] == 'at_home').astype(int)
df['Fjob_health'] = (df['Fjob'] == 'health').astype(int)
df['Fjob_teacher'] = (df['Fjob'] == 'teacher').astype(int)
df['Fjob_services'] = (df['Fjob'] == 'services').astype(int)
df = df.drop(['Fjob'], axis = 1)

df['reason_home'] = (df['reason'] == 'home').astype(int)
df['reason_reputation'] = (df['reason'] == 'reputation').astype(int)
df['reason_course'] = (df['reason'] == 'course').astype(int)
df = df.drop(['reason'], axis = 1)

df['schoolsup'] = (df['schoolsup'] == 'yes').astype(int)
df['famsup'] = (df['famsup'] == 'yes').astype(int)
df['paid'] = (df['paid'] == 'yes').astype(int)
df['activities'] = (df['activities'] == 'yes').astype(int)
df['nursery'] = (df['nursery'] == 'yes').astype(int)
df['higher'] = (df['higher'] == 'yes').astype(int)
df['internet'] = (df['internet'] == 'yes').astype(int)
df['romantic'] = (df['romantic'] == 'yes').astype(int)

df['Walc_bin'] = (df['Walc'] > 3).astype(int)
df['Dalc_bin'] = (df['Dalc'] > 1).astype(int)

In [22]:
df.head()

age  Medu  Fedu  traveltime  studytime  failures  schoolsup  famsup  paid  \
0   18     4     4           2          2         0          1       0     0   
1   17     1     1           1          2         0          0       1     0   
2   15     1     1           1          2         3          1       0     1   
3   15     4     2           1          3         0          0       1     1   
4   16     3     3           1          2         0          0       1     1   

   activities    ...     Mjob_services  Fjob_at_home  Fjob_health  \
0           0    ...                 0             0            0   
1           0    ...                 0             0            0   
2           0    ...                 0             0            0   
3           1    ...                 0             0            0   
4           0    ...                 0             0            0   

   Fjob_teacher  Fjob_services  reason_home  reason_reputation  reason_course  \
0             1              0            0                  0              1   
1             0              0            0                  0              1   
2             0              0            0                  0              0   
3             0              1            1                  0              0   
4             0              0            1                  0              0   

   Walc_bin  Dalc_bin  
0         0         0  
1         0         0  
2         0         1  
3         0         0  
4         0         0  

[5 rows x 44 columns]

In [23]:
df.columns

Index(['age', 'Medu', 'Fedu', 'traveltime', 'studytime', 'failures',
       'schoolsup', 'famsup', 'paid', 'activities', 'nursery', 'higher',
       'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc', 'Walc',
       'health', 'absences', 'G1', 'G2', 'G3', 'rural', 'P_apart', 'school_GP',
       'female', 'famsize_bin', 'guardian_mother', 'guardian_father',
       'Mjob_at_home', 'Mjob_health', 'Mjob_teacher', 'Mjob_services',
       'Fjob_at_home', 'Fjob_health', 'Fjob_teacher', 'Fjob_services',
       'reason_home', 'reason_reputation', 'reason_course', 'Walc_bin',
       'Dalc_bin'],
      dtype='object')

## C. Predicting G3

It can has about 20 values. So we can use
* Classication for data with discrete labels
* Regression for data with continuous labels

In [25]:
from sklearn import preprocessing
from sklearn import linear_model
from sklearn import metrics
from sklearn.naive_bayes import BernoulliNB
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

## C1. Trying Classification
### Preparing data

In [26]:
X = df.drop(['G3', 'G2', 'G1'], axis = 1)
X.describe()

age         Medu         Fedu   traveltime    studytime  \
count  1044.000000  1044.000000  1044.000000  1044.000000  1044.000000   
mean     16.726054     2.603448     2.387931     1.522989     1.970307   
std       1.239975     1.124907     1.099938     0.731727     0.834353   
min      15.000000     0.000000     0.000000     1.000000     1.000000   
25%      16.000000     2.000000     1.000000     1.000000     1.000000   
50%      17.000000     3.000000     2.000000     1.000000     2.000000   
75%      18.000000     4.000000     3.000000     2.000000     2.000000   
max      22.000000     4.000000     4.000000     4.000000     4.000000   

          failures    schoolsup       famsup         paid   activities  \
count  1044.000000  1044.000000  1044.000000  1044.000000  1044.000000   
mean      0.264368     0.113985     0.613027     0.210728     0.494253   
std       0.656142     0.317945     0.487291     0.408021     0.500207   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     1.000000     0.000000     0.000000   
75%       0.000000     0.000000     1.000000     0.000000     1.000000   
max       3.000000     1.000000     1.000000     1.000000     1.000000   

          ...       Mjob_services  Fjob_at_home  Fjob_health  Fjob_teacher  \
count     ...         1044.000000   1044.000000  1044.000000   1044.000000   
mean      ...            0.228927      0.059387     0.039272      0.062261   
std       ...            0.420344      0.236461     0.194335      0.241744   
min       ...            0.000000      0.000000     0.000000      0.000000   
25%       ...            0.000000      0.000000     0.000000      0.000000   
50%       ...            0.000000      0.000000     0.000000      0.000000   
75%       ...            0.000000      0.000000     0.000000      0.000000   
max       ...            1.000000      1.000000     1.000000      1.000000   

       Fjob_services  reason_home  reason_reputation  reason_course  \
count    1044.000000  1044.000000        1044.000000    1044.000000   
mean        0.279693     0.247126           0.237548       0.411877   
std         0.449064     0.431548           0.425785       0.492409   
min         0.000000     0.000000           0.000000       0.000000   
25%         0.000000     0.000000           0.000000       0.000000   
50%         0.000000     0.000000           0.000000       0.000000   
75%         1.000000     0.000000           0.000000       1.000000   
max         1.000000     1.000000           1.000000       1.000000   

          Walc_bin     Dalc_bin  
count  1044.000000  1044.000000  
mean      0.202107     0.303640  
std       0.401764     0.460049  
min       0.000000     0.000000  
25%       0.000000     0.000000  
50%       0.000000     0.000000  
75%       0.000000     1.000000  
max       1.000000     1.000000  

[8 rows x 41 columns]

In [29]:
#y = pd.DataFrame()
# y["0"] = (df['G3'] <= 5).astype(int)
# y["1"] = ((df['G3'] >5) & (df['G3']<=10)).astype(int)
# y["2"] = ((df['G3'] >10) & (df['G3']<=15)).astype(int)
# y["3"] = ((df['G3'] >15)).astype(int)

y = pd.cut(df['G3'], [-1, 7, 9, 11, 14, 25], labels=['0', '1', '2', '3', '4'])
y = pd.DataFrame(y)
y.head()

G3
0  0
1  0
2  2
3  4
4  2

### since there are lots of students having score between 7 to 12

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X, y,  test_size=0.2)

### 1. Random Forest

In [31]:
clf = RandomForestClassifier(n_estimators=100)
# lr.fit(X_train, y_train)
# pred_Y_test = lr.predict_proba(X_test)
scores = cross_val_score(clf, X, y.values.ravel(), cv=10)
scores

array([0.37735849, 0.33962264, 0.31132075, 0.33018868, 0.28846154,
       0.30769231, 0.33980583, 0.3592233 , 0.34951456, 0.38834951])

In [33]:
clf.fit(X_train, y_train.values.ravel())

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [34]:
pred_y_test = clf.predict(X_test)
pred_y_test

array(['4', '2', '1', '2', '2', '1', '2', '2', '3', '4', '3', '1', '2',
       '0', '4', '3', '3', '2', '1', '2', '1', '3', '3', '3', '2', '3',
       '4', '2', '2', '3', '4', '1', '0', '2', '3', '3', '3', '4', '3',
       '3', '2', '2', '1', '3', '2', '2', '3', '2', '1', '3', '4', '2',
       '2', '4', '2', '3', '2', '2', '0', '4', '2', '2', '2', '2', '2',
       '2', '1', '2', '3', '3', '2', '1', '4', '4', '3', '3', '3', '4',
       '3', '3', '0', '2', '1', '2', '3', '3', '2', '0', '2', '2', '2',
       '2', '1', '3', '4', '2', '3', '2', '2', '2', '2', '3', '4', '2',
       '2', '2', '3', '3', '3', '3', '2', '3', '2', '0', '3', '3', '2',
       '4', '3', '3', '3', '4', '2', '2', '1', '2', '4', '4', '2', '3',
       '1', '3', '4', '3', '4', '2', '2', '4', '3', '2', '3', '2', '3',
       '1', '4', '3', '3', '2', '3', '0', '3', '3', '2', '3', '3', '4',
       '2', '3', '0', '2', '2', '2', '3', '2', '2', '4', '3', '3', '1',
       '3', '3', '3', '3', '3', '2', '2', '2', '2', '2', '4', '1

In [35]:
print('Accuracy: ' + str(clf.score(X_test, y_test)))
print('Precision: ' + str(metrics.precision_score(y_test, pred_y_test, average=None)))
print('F1 Score: ' + str(metrics.f1_score(y_test, pred_y_test,  average=None)))

Accuracy: 0.32057416267942584
Precision: [0.5        0.05555556 0.31168831 0.28947368 0.53571429]
F1 Score: [0.25       0.05128205 0.36090226 0.31884058 0.44117647]


In [37]:
metrics.confusion_matrix(y_test, pred_y_test)

array([[ 5,  6, 13,  6,  0],
       [ 0,  1, 12,  7,  1],
       [ 2,  6, 24, 22,  2],
       [ 2,  5, 23, 22, 10],
       [ 1,  0,  5, 19, 15]])

### 2. Native Bayes

In [38]:
clf_b = BernoulliNB()
# lr.fit(X_train, y_train)
# pred_Y_test = lr.predict_proba(X_test)
scores = cross_val_score(clf_b, X, y.values.ravel(), cv=10)
scores

array([0.33018868, 0.35849057, 0.27358491, 0.33962264, 0.39423077,
       0.31730769, 0.40776699, 0.48543689, 0.39805825, 0.36893204])

In [39]:
clf_b.fit(X_train, y_train.values.ravel())

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [40]:
pred_y_test = clf_b.predict(X_test)
pred_y_test

array(['4', '1', '3', '1', '2', '4', '2', '2', '3', '4', '3', '1', '2',
       '3', '4', '3', '4', '1', '2', '0', '1', '2', '2', '2', '3', '2',
       '4', '2', '2', '3', '3', '2', '2', '3', '3', '3', '2', '4', '1',
       '4', '3', '2', '2', '2', '3', '3', '4', '2', '3', '3', '4', '3',
       '2', '4', '2', '2', '4', '4', '0', '3', '2', '2', '2', '2', '4',
       '2', '1', '2', '2', '3', '2', '3', '4', '3', '3', '4', '2', '3',
       '3', '3', '2', '2', '0', '2', '3', '3', '3', '3', '2', '2', '3',
       '2', '2', '3', '2', '4', '0', '4', '1', '2', '3', '3', '4', '2',
       '4', '2', '3', '4', '4', '3', '2', '3', '2', '4', '2', '3', '2',
       '3', '4', '3', '3', '4', '0', '0', '3', '2', '2', '3', '3', '3',
       '0', '2', '2', '3', '4', '3', '0', '3', '3', '0', '2', '4', '4',
       '4', '2', '2', '3', '2', '3', '0', '2', '3', '3', '2', '2', '4',
       '2', '3', '0', '3', '4', '2', '3', '3', '0', '4', '3', '4', '4',
       '2', '2', '2', '3', '4', '3', '2', '2', '2', '2', '3', '3

In [41]:
print('Accuracy: ' + str(clf_b.score(X_test, y_test)))
print('Precision: ' + str(metrics.precision_score(y_test, pred_y_test, average=None)))
print('F1 Score: ' + str(metrics.f1_score(y_test, pred_y_test,  average=None)))

Accuracy: 0.3588516746411483
Precision: [0.84615385 0.27272727 0.38888889 0.30985915 0.26190476]
F1 Score: [0.51162791 0.1875     0.4375     0.33082707 0.26829268]


In [42]:
metrics.confusion_matrix(y_test, pred_y_test)

array([[11,  3,  8,  7,  1],
       [ 0,  3, 12,  2,  4],
       [ 1,  5, 28, 18,  4],
       [ 1,  0, 17, 22, 22],
       [ 0,  0,  7, 22, 11]])

### 3. KNeighborsClassifier

In [43]:
from sklearn.neighbors import KNeighborsClassifier

### checking model for different n_neighbours value

In [44]:
clf_k_1 = KNeighborsClassifier(n_neighbors=10)
scores = cross_val_score(clf_k_1, X, y.values.ravel(), cv=10)
scores

array([0.27358491, 0.27358491, 0.25471698, 0.35849057, 0.29807692,
       0.32692308, 0.24271845, 0.33980583, 0.33980583, 0.36893204])

In [45]:
clf_k_2 = KNeighborsClassifier(n_neighbors=30)
scores = cross_val_score(clf_k_2, X, y.values.ravel(), cv=10)
scores

array([0.30188679, 0.32075472, 0.26415094, 0.33018868, 0.33653846,
       0.31730769, 0.3592233 , 0.32038835, 0.3592233 , 0.42718447])

In [46]:
clf_k_3 = KNeighborsClassifier(n_neighbors=20)
scores = cross_val_score(clf_k_3, X, y.values.ravel(), cv=10)
scores

array([0.30188679, 0.29245283, 0.22641509, 0.31132075, 0.29807692,
       0.35576923, 0.34951456, 0.30097087, 0.32038835, 0.4368932 ])

In [47]:
clf_k_4 = KNeighborsClassifier(n_neighbors=15)
scores = cross_val_score(clf_k_4, X, y.values.ravel(), cv=10)
scores

array([0.29245283, 0.30188679, 0.24528302, 0.31132075, 0.27884615,
       0.29807692, 0.29126214, 0.34951456, 0.34951456, 0.45631068])

### clearly n_neighbors=15 has better scores.

In [48]:
clf_k_4.fit(X_train, y_train.values.ravel())

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=15, p=2,
           weights='uniform')

In [49]:
pred_y_test = clf_k_4.predict(X_test)
pred_y_test

array(['4', '1', '3', '1', '2', '3', '2', '1', '3', '2', '3', '3', '3',
       '2', '4', '3', '3', '2', '2', '2', '2', '3', '2', '2', '3', '2',
       '3', '2', '2', '2', '4', '2', '2', '2', '4', '3', '3', '4', '1',
       '4', '3', '2', '1', '3', '3', '2', '3', '3', '3', '3', '4', '3',
       '2', '4', '0', '4', '3', '3', '3', '2', '4', '2', '1', '2', '3',
       '2', '2', '2', '3', '2', '2', '2', '4', '3', '2', '4', '3', '3',
       '3', '4', '2', '2', '3', '2', '3', '3', '3', '2', '3', '1', '3',
       '2', '3', '2', '3', '4', '3', '3', '2', '3', '2', '1', '3', '2',
       '3', '2', '4', '2', '3', '2', '2', '3', '2', '3', '3', '3', '2',
       '3', '3', '3', '3', '2', '4', '0', '3', '2', '3', '3', '4', '3',
       '3', '3', '3', '2', '2', '2', '3', '3', '2', '4', '3', '3', '4',
       '4', '4', '3', '3', '2', '3', '0', '3', '2', '2', '0', '2', '3',
       '2', '4', '0', '3', '3', '2', '3', '2', '2', '3', '3', '2', '3',
       '2', '4', '2', '3', '3', '2', '2', '1', '2', '2', '3', '2

In [50]:
print('Accuracy: ' + str(clf_k_4.score(X_test, y_test)))
print('Precision: ' + str(metrics.precision_score(y_test, pred_y_test, average=None)))
print('F1 Score: ' + str(metrics.f1_score(y_test, pred_y_test,  average=None)))

Accuracy: 0.3492822966507177
Precision: [0.57142857 0.5        0.39726027 0.29032258 0.30769231]
F1 Score: [0.21621622 0.32258065 0.4496124  0.3483871  0.24242424]


In [51]:
metrics.confusion_matrix(y_test, pred_y_test)

array([[ 4,  2,  9, 12,  3],
       [ 0,  5,  8,  8,  0],
       [ 3,  2, 29, 20,  2],
       [ 0,  1, 21, 27, 13],
       [ 0,  0,  6, 26,  8]])

## C2. Trying Regression
### Preparing data

In [52]:
y = df['G3']

In [53]:
X_train, X_test, y_train, y_test = train_test_split(X, y,  test_size=0.2)

### Simple Linear Regression (Lasso)

In [54]:
from sklearn.linear_model import Lasso

In [57]:
lasso = Lasso(alpha=1, fit_intercept=False, max_iter=1000)

In [58]:
lasso.fit(X_train, y_train.values.ravel())

Lasso(alpha=1, copy_X=True, fit_intercept=False, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [59]:
pred_y_test = lasso.predict(X_test)

In [62]:
mse = np.mean((y_test - pred_y_test)**2)
mse

13.72537261899845

In [63]:
print(y_test.values.ravel()-pred_y_test)

[-2.22142983e+00  1.88040135e+00  2.38059823e+00  3.74974387e+00
  2.16569607e+00  2.01157441e+00  4.88035166e-01  2.48803517e+00
 -1.81083974e+00 -1.18812323e+01 -4.85764629e+00  5.38072005e+00
  6.66014774e-01 -9.88425595e-01 -3.33875077e+00  1.90386554e+00
  7.61597793e-01  2.64203500e+00 -4.90842601e-02  2.85705899e+00
 -1.18812323e+01  2.05862461e+00 -1.17548248e+01 -1.38580098e+00
  4.04184241e-01  6.66014774e-01 -1.23852403e+00 -1.51220849e+00
  7.84940155e-01 -1.04634393e-01  5.48803517e+00  2.65428268e+00
  3.38072005e+00  3.50385939e-02  1.48803517e+00  1.28525886e+00
 -1.59593759e+00  6.54657381e+00 -3.60230757e+00  5.74974387e+00
 -1.17548248e+01  1.38072005e+00 -4.14306284e+00  1.89799949e+00
 -7.31238782e-01  3.90398736e+00  1.16962323e-02  1.91571946e+00
 -3.43323329e+00  3.01169623e+00  4.15916335e-01  4.48803517e+00
 -4.22479871e-01  2.38072005e+00  1.85705899e+00  2.76147597e+00
  4.22608281e+00  1.64951713e+00 -1.86201808e+00  8.20136438e-01
  3.48803517e+00  1.22608

#### We can see that predicted values are very close to actual values

## Conclusion

1. Clearly the Lasso regression is the best model as compared to other models.
2. Random Forest classification has the worst results (confusion matrix)
3. From classification models, Native Bayes is best
4. KNeighborsClassifier is giving best results for n_neighbors=30.